//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookBlogger.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string EventType { get; set; }
        public string LoginName { get; set; }
        public string SchemaName { get; set; }
        public string TableName { get; set; }
    }
}
