//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookBlogger.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookBloggerEntities : DbContext
    {
        public BookBloggerEntities()
            : base("name=BookBloggerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int uspAddUser(string pUsername, string pPassword, string pFirstName, string pLastName, Nullable<bool> pIsAdmin, Nullable<System.DateTime> pCreated)
        {
            var pUsernameParameter = pUsername != null ?
                new ObjectParameter("pUsername", pUsername) :
                new ObjectParameter("pUsername", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            var pFirstNameParameter = pFirstName != null ?
                new ObjectParameter("pFirstName", pFirstName) :
                new ObjectParameter("pFirstName", typeof(string));
    
            var pLastNameParameter = pLastName != null ?
                new ObjectParameter("pLastName", pLastName) :
                new ObjectParameter("pLastName", typeof(string));
    
            var pIsAdminParameter = pIsAdmin.HasValue ?
                new ObjectParameter("pIsAdmin", pIsAdmin) :
                new ObjectParameter("pIsAdmin", typeof(bool));
    
            var pCreatedParameter = pCreated.HasValue ?
                new ObjectParameter("pCreated", pCreated) :
                new ObjectParameter("pCreated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspAddUser", pUsernameParameter, pPasswordParameter, pFirstNameParameter, pLastNameParameter, pIsAdminParameter, pCreatedParameter);
        }
    }
}
